<?php
/*
 * Turiknox_Webgains

 * @category   Turiknox
 * @package    Turiknox_Webgains
 * @copyright  Copyright (c) 2017 Turiknox
 * @license    https://github.com/Turiknox/magento-webgains-tracking/blob/master/LICENSE.md
 * @version    1.0.0
 */
?>
<?php
    $orderReference = $this->escapeHtml($this->getOrderIncrementId());
    $orderTotal = $this->getGrandTotal();
    $webgainsEventId = $this->escapeHtml($this->getWebgainsEventId());
    $webgainsVersion = $this->getWebgainsVersion();
    $webgainsProgramId = $this->escapeHtml($this->getWebgainsProgramId());
    $shippingAmount = $this->getShippingAmount();
    $lang = Mage::app()->getLocale()->getLocaleCode();
    $currency = $this->getCurrency();
    $couponCode = $this->escapeHtml($this->getCouponCode());
    $items = $this->escapeHtml($this->getWebGainsItemData());
?>
<?php if ($this->isEnabled()): ?>
    <script type="text/javascript">
        var wgOrderReference = '<?php echo $orderReference; ?>';
        var wgOrderValue = '<?php echo $orderTotal; ?>';
        var wgEventID = <?php echo $webgainsEventId; ?>;
        var wgComment = "";
        var wgLang = '<?php echo $lang; ?>';
        var wgsLang = "javascript-client";
        var wgVersion = '<?php echo $webgainsVersion; ?>';
        var wgProgramID = <?php echo $webgainsProgramId; ?>;
        var wgSubDomain = "track";
        var wgCheckSum = "";
        var wgItems = '<?php echo $items; ?>';
        var wgVoucherCode = '<?php echo $couponCode; ?>';
        var wgCustomerID = "";
        var wgCurrency = '<?php echo $currency; ?>';

        if(location.protocol.toLowerCase() === "https:") wgProtocol="https";
        else wgProtocol = "http";
        wgUri = wgProtocol + "://" + wgSubDomain + ".webgains.com/transaction.html" + "?wgver=" + wgVersion +
            "&wgprotocol=" + wgProtocol + "&wgsubdomain=" + wgSubDomain + "&wgslang=" + wgsLang + "&wglang=" + wgLang +
            "&wgprogramid=" + wgProgramID + "&wgeventid=" + wgEventID + "&wgvalue=" + wgOrderValue + "&wgchecksum=" +
            wgCheckSum + "&wgorderreference="  + wgOrderReference + "&wgcomment=" + encodeURIComponent(wgComment) + "&wglocation=" +
            encodeURIComponent(document.referrer) + "&wgitems=" + encodeURIComponent(wgItems) + "&wgcustomerid=" + encodeURIComponent(wgCustomerID) +
            "&wgvouchercode=" + encodeURIComponent(wgVoucherCode) + "&wgCurrency=" + encodeURIComponent(wgCurrency);
        document.write('<sc'+'ript language="JavaScript"  type="text/javascript" src="'+wgUri+'"></sc'+'ript>');
    </script>
    <noscript>
        <img src="http://track.webgains.com/transaction.html?wgver=<?php echo $webgainsVersion; ?>&wgprogramid=<?php echo $webgainsProgramId; ?>&wgrs=1&wgvalue=<?php echo $orderTotal; ?>&wgeventid=<?php echo $webgainsEventId; ?>&wgorderreference=<?php echo $orderReference; ?>&wgitems=<?php echo $items; ?>&wgvouchercode=<?php echo $couponCode; ?>&wgcustomerid=&wgCurrency=<?php echo $currency; ?>" alt="" />
    </noscript>
<?php endif; ?>